specVersion: 0.2.0
name: slp-kusama-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/slp-kusama-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xb7426168a3623c663511e7b891b2bf177ca79f9556bdf13403239845a157464f'
  endpoint: 'wss://kusama-rpc.devnet.liebi.com/ws'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: staking
            method: EraPaid
        - handler: handleStakingBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleStakinUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleStakingWithdrawn
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Withdrawn
#        - handler: handleStakingKicked
#          kind: substrate/EventHandler
#          filter:
#            module: staking
#            method: Kicked
#        - handler: handleStakingChilled
#          kind: substrate/EventHandler
#          filter:
#            module: staking
#            method: Chilled
#        - handler: handleStakingSlashed
#          kind: substrate/EventHandler
#          filter:
#            module: staking
#            method: Slashed
        - handler: handleStakingPayoutstarte
          kind: substrate/EventHandler
          filter:
            module: staking
            method: PayoutStarted
        - handler: handleParaInherent
          kind: substrate/CallHandler
          filter:
            module: paraInherent
            method: enter
            success: true