specVersion: 0.2.0
name: slp-kusama-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/salp-confirm-kusama-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: 'wss://kusama-rpc.polkadot.io'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 11628200
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: staking
            method: EraPaid
        - handler: handleStakingBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleStakinUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleStakingWithdrawn
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Withdrawn
        - handler: handleStakingKicked
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Kicked
        - handler: handleStakingChilled
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Chilled
        - handler: handleStakingSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleStakingPayoutstarte
          kind: substrate/EventHandler
          filter:
            module: staking
            method: PayoutStarted